README.md
lambdas/api/index.js
libs/api.js
libs/es.js
serverless.yml
utils/http-methods.js

My overall goal was to change from a:
`POST /collections/<collectionId>/items/<itemId>/edit`
to
`PATCH /collections/<collectionId>/items/<itemId>`
Which was more RESTful and also conforms to the stac-api's Transaction specification: https://github.com/radiantearth/stac-api-spec/tree/master/extensions/transaction
An /edit path is more traditionally used to render a HTML form which eventually will post to a PUT/PATCH endpoint.
I also adjusted aspects of areas I was touching directly:
- The above route change
- Ability to easily toggle whether Transaction extension endpoints are available
- Simple HTTP constant utils introduced
- Fixed a bug where we required a blank `properties` param even if not are being modified
We have a DIY routing approach inside api.js. Previously it was working with …

Improve partial item editing / enabling of Transactions extensions

---

CHANGELOG.md
fixtures/collections.js
fixtures/items.js
libs/es.js
libs/esStream.js
package.json
serverless.yml

Update from elasticsearch 6.8 to 7.9, resolves #65 
Also updated mappings to exclude objects like `links` and `assets`, since they are not searchable anyway through the API. Resolves #69 and #68

elasticsearch 7

---

serverless.yml

t3.small is cheaper than t2.small (and newer generation hardware). In addition it allows setting security configuration if desired, such as `NodeToNodeEncryptionOptions` and `EncryptionAtRestOptions`. This PR also contains a config change to force HTTPS, which is desired in all cases

Set default instance type to t3.small and enforce HTTPS

---

README.md
lambdas/api/index.js
serverless.yml

Hi All! 
**Thanks for doing what you do for the greater geospatial community! This has been a wonderfully helpful project and I cannot thank you enough for keeping it open source.** 
I split these into 3 commits so they're easier to review:
1. Upping the SQS `VisibilityTimeout` to above the lambda one cleared a Serverless deployment issue
2. `STAC_API_URL` wasn't called anywhere and `STAC_ROOT_URL` wasn't populating, so I swapped `STAC_API_URL` into the API Lambda (not sure if I was right here or not)
3. Added your correct endpoint to your README.md
Thanks again! 🍻

SQS Timeout

---

libs/api.js
tests/integration/test_api.js

The issue was that I was converting a string to a JSON string which adds extra quotes.
I added integration test for this fix to make sure this is not broken again. Will further extend tests to check that other parameters are not malformed in next link.

Only JSON.stringify Object, not string

---

libs/esStream.js

Closes #152
The issue was that the `ElasticSearchWritableStream` was closing its client when it was destroyed, which ended up closing the clients that other operations were trying to use.

Fix bug where all ES connections in pool were dead

---

.github/workflows/push.yaml
package-lock.json
package.json
tsconfig.json

Add an `npm run typecheck` script that will use the TypeScript compiler to perform static code analysis. By default it will only check a JavaScript file if it starts with `// @ts-check`. None of them do but, as we move forward, we can use that to help verify the correctness of our code.
To be clear, this is not converting this project's code to TypeScript. It's just using the TypeScript compiler to help detect bugs.

Add ability to use tsc for static code analysis

---

.github/pull_request_template.md
.github/workflows/push.yaml
src/lambdas/api/webpack.config.js

**Related Issue(s):** n/a
1. fix incorrect location of api.yaml in webpack config
2. run build for all PRs

Fix npm build problem

---

src/lib/api.js
tests/system/test-api-get-api.js
tests/unit/test-api-search.js

- n/a
1. advertise OpenAPI yaml media type instead of json media type, to match what the /api endpoint actually returns.

fix service-desc link relation type to use OpenAPI yaml media type

---

src/lambdas/api/app.js
src/lambdas/api/middleware/add-endpoint.js

As we add more middleware to the API, we're going to want to keep it organized.
This PR moves the `addEndpoint` middleware into its own file

Move addEndpoint middleware

---

CHANGELOG.md
src/lambdas/api/middleware/add-endpoint.js
tests/system/test-api-get-root.js

Closes #130
If a client includes the header `X-STAC-Endpoint`, that value will be used as the STAC endpoint when building link hrefs. The previous implementation was not particularly flexible, and could not handle the case where a client needed the link hrefs to use `http` for the schema. (This was an issue for running against a local stac instance.)

Add support for X-STAC-Endpoint header

---

fixtures/dynamicTemplates.js

- #235 
1. remove match requirement of string for these fields, since that would never match

change proj:centroid and proj:geometry to not have type match on string

---

src/lib/es.js
tests/system/test-api-search-post.js
tests/unit/test-es.js

- #243 
1. instead of using `constant_score` and `must`, use `bool` and `filter`. This is a more typical way to express these queries, since they are filtering (similarly to how SQL select works) rather than doing scored sorting (the default ES way). 
2. using `filter` also allows these query results to be cached on the ES side, so performance will be better.

replace constant_score and must with bool and filter for ES queries

---

CHANGELOG.md
package-lock.json
package.json
src/lib/api.js
tests/unit/test-api-extractIntersects.js

- https://github.com/stac-utils/stac-server/issues/246
1. remove geoson-validation library because it is LGPL 3
2. follow on issue to resolve b/c of this change is 
- https://github.com/stac-utils/stac-server/issues/245

remove dependency on geojson-validation because it's LGPL 3

---

src/lambdas/api/middleware/add-endpoint.js

- #238 
1.  Allow use of STAC_API_ROOTPATH to set an api gw stage path prefix  when STAC_API_URL is not set

Allow use of STAC_API_ROOTPATH to set an api gw stage path prefix

---

CHANGELOG.md
fixtures/items.js

- # https://github.com/stac-utils/stac-server/issues/249
1. Added mapping within index for the default sort keys of 'id' and 'collection' 

Added mappings for default sort keys

---

CHANGELOG.md
src/lib/api.js

…in the result of a GET request
- https://github.com/stac-utils/stac-server/issues/214
1. Added proper value for 'collections' parameter in the next page link in the result of a GET request

Added proper value for GET 'collections' parameter in link to next page

---

package-lock.json
package.json
tsconfig.json

- n/a
1. fix a few dependency versions that weren't updated from 14 to 16 when the node version was bumped

fix a few packages that weren't updated during the node 16 update

---

src/lib/api.js
tests/unit/test-api-limit.js

- #312 
1. a limit over 10000 will act as if the limit was 10000, instead of returning a 400. This is a recent change the the STAC API spec.

limit above max no error

---

CHANGELOG.md
src/lib/api.js

- n/a
1. Add both GET and POST search link relations to root (landing page). This is how an API advertises it supports both GET and POST to the /search endpoint. 

add search links in root fro both GET and POST

---

src/lib/es.js

- N/A
1. Fix typo in variable name: `exisiting` -> `existing`

Fix a typo in a variable name

---

CHANGELOG.md
README.md
serverless.example.yml
src/lib/es.js
src/lib/esClient.js
src/lib/esStream.js

- https://github.com/stac-utils/stac-server/issues/316
1. Add support for fine-grained access control, where stac-server must authenticate to OpenSearch with a username and password, rather than getting full access via IAM permissions. This username and password can be stored as a Secrets Manager secret and retrieved by ARN
2. Rename ES_HOST and ES_BATCH_SIZE variables (with backwards compatibility)
3. Change the search's index restriction to also cover the "dot" indices created by opensearch

Add support for fine-grained access control

---

README.md

- https://github.com/stac-utils/stac-server/issues/306
1. Add examples of calling the server, specifically with an example of the query parameter for GET being JSON. This additional documentation was user-requested.

add note about usage w/ mention of get query json

---

CHANGELOG.md
src/lib/api.js

- https://github.com/stac-utils/stac-server/issues/302
Fix various issues with link relations, including:
1. missing `type` fields
2. unnecessary trailing `/` on root endpoint
3. add missing self, root, and parent to collections endpoint

fix various issues with link relations

---

bin/system-tests.sh
package.json

- n/a
1. run system tests with `--serial` flag rather than using deprecated ava config file param

ava should use a cmdline flag to serialize integration tests rather than the deprecated 'serial' config property

---

README.md
src/lambdas/pre-hook/index.js
tests/unit/test-pre-hook.js

- n/a
1. change expected secrets value for auth pre-hook from a string to an array.
2. Change the default permission required to "write" until conditional logic that checks the verb and path can be implemented

auth pre-hook: change expected value for secrets manager secret from string to array, require write permission

---

package.json
src/lambdas/api/local.ts

- n/a
1. Fix `serve` script by correctly importing the app in local.ts and enabling ESM module support in nodemon 

fix run serve script

---

CHANGELOG.md
src/lib/api.js

- n/a
1. Use `storage:region` field for determining which region thumbnail URLs should be generated against.

use storage:region for thumbnail generation

---

CHANGELOG.md
src/lib/database.js
tests/system/test-api-search-post.js

- https://github.com/stac-utils/stac-server/issues/405
1. Add `stac_version` to the default fields returned when the `fields` value is empty. This is a recent change to the fields extension (1.0.0-rc.3). 

add stac_version to the default fields returned when that parameter is blank

---

CHANGELOG.md
README.md
bin/build-openapi.sh
src/lambdas/api/openapi.yaml
src/lib/api.js

- n/a
1. Update "foundation" conformance classes to 1.0.0-rc.4
2. Update fields to 1.0.0-rc.3 (extensions are independently versioned from foundation now)
3. Remove transactions from published api spec, as this is no longer published in the same location.

update conformance to STAC API 1.0.0-rc.4

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/lambdas/api/openapi.yaml
src/lib/api.js

- n/a
1. Update STAC API version references to 1.0.0
2. Prep for stac-server 1.0.0 release

1.0.0 release prep

---

README.md

- #467
1. Updates to README regarding the migration from ElasticSearch to OpenSearch

Updates Migration Docs

---

CHANGELOG.md
package.json
src/lambdas/api/app.js

- [# 458](https://github.com/stac-utils/stac-server/issues/458)
This commit addresses two issues:
* The current morgan implementation does not pass through the request id generated by the API Gateway, making it difficult to filter to a given bad request. By writing output to console out, we are able to capture this id as part of the log statement.
* The current morgan implementation will only log if a request is successful due to the fact that it is async, which means that if a lambda timeout is reached we will not see the request that caused the timeout. This is problematic, because as an operator, we may want to see if this timeout is reproduceable. Adding  with minimal additional output will allow us to capture the start of the request. This …

Adds API Gateway transaction ID to requests and logs immediately #458

---

CHANGELOG.md
src/lib/ingest.js

- #486
1. The `type` field is required in STAC API 1.0.0 and using that field is preferable to a heuristic based on other field values.

 Use the type field to determine if ingest is collection or item

---

src/lib/ingest.js
tests/system/test-ingest.js

- #45
This commit addresses intermittent failures in system tests related to SNS message publishing. Adding console.log statements revealed 2 situations
- Test assertions were running before an item ingest message was published
- Calling `purgeQeue` did not appear to actually empty the SNS queue
This commit moves an await call to guarantee that messages are published to SNS before trying to assert that they have been published and replaces a call to `purgeQueue` will calling `receiveMessage` in a loop.
Here is an example of an intermittent test failure that lead to troubleshooting and creating this PR https://github.com/stac-utils/stac-server/actions/runs/5049084598/jobs/9058087110
These are the `console.log` messages I added to help debug this …

Await SNS message publishing and replace queue purge test helper

---

CHANGELOG.md
src/lib/sns.js
src/lib/stac-utils.js
tests/system/test-ingest.js
tests/unit/test-stac-utils.js

- #45 
1. Add `datetime`, `start_datetime`, and `end_datetime` string attributes to post-ingest SNS messages
2. Add `start_unix_epoch_ms_offset` and `end_unix_epoch_ms_offset`number attributes to post-ingest SNS messages
3. Add `bbox.ll_lon`, `bbox.ll_lat`, `bbox.ur_lon`, `bbox.ur_lat` number attributes to post-ingest SNS messages
@jkeifer provided guidance based on the Cirrus implementation of filterable SNS message attributes
https://github.com/cirrus-geo/cirrus-geo/blob/35f3de5b9c99b2295b51cccb7ee2e12f64be3f5a/src/cirrus/builtins/tasks/publish/lambda_function.py#L46-L93

Add datetime and bbox attributes to post-ingest SNS messages

---

CHANGELOG.md
package-lock.json
src/lib/database.js

- n/a
1. remove restriction of 2000 buckets for grid_code_frequency and grid_code_landsat_frequency buckets. This is no longer necessary because a client must request each aggregation they want to perform, so these won't automatically stomp on the buckets of other aggregations.

remove restriction of 2000 on grid_code_frequency and grid_code_landsat_frequency buckets

---

CHANGELOG.md
README.md
package.json
serverless.example.yml

- n/a
1. Add example of configuring API Gateway logging
This will log to a CloudWatch group named `/aws/api-gateway/{service}-{stage}`.

API Gateway logging example

---

CHANGELOG.md
package-lock.json
package.json
src/lib/api.js
tests/system/test-api-search-post.js

- https://github.com/stac-utils/stac-server/issues/549
1. revert validation of geometry until it can be fixed
2. release prep for 2.2.2

revert intersects geometry validation

---

.github/workflows/push.yaml
CHANGELOG.md
README.md
docker-compose.yml
serverless.example.yml

- https://github.com/stac-utils/stac-server/issues/561
1. Update default OpenSearch version to 2.7

update default OpenSearch to 2.7

---

.github/workflows/push.yaml
CHANGELOG.md
docker-compose.yml
src/lambdas/api/index.js
src/lambdas/api/webpack.config.js
src/lambdas/ingest/webpack.config.js
src/lambdas/post-hook/webpack.config.js
src/lambdas/pre-hook/webpack.config.js
src/lib/database-client.js
tests/unit/test-ingest-1.js

- n/a
1. Removes usage of aws-sdk, which just happened to work locally because of a transient dev dependency, but failed when deployed as a lambda
2. Updates localstack to use version 3, since apparently version 2 no longer works with the sdk changes or something?

remove aws-sdk usage

---

CHANGELOG.md
src/lambdas/ingest/index.js
src/lib/ingest.js
tests/helpers/ingest.js
tests/system/test-ingest.js

- https://github.com/stac-utils/stac-server/issues/660
1.  Currently, if any item fails to ingest, a message is logged, but the lambda always returns success. This changes that, so if any item fails to ingest, the lambda will fail too.

ingest failures will propagate to a lambda failure

---

CHANGELOG.md
package-lock.json
package.json
src/lib/api.js

- https://github.com/stac-utils/stac-server/issues/589
1. when sortby is used, correctly return a next parameter in the next link
2. release prep for 3.5.0

fix bug where next param was missing when sortby was specified

---

README.md

- n/a
1. Add migration warning about the OpenSearch 2.11 index issue

add warning about indices causing a problem in OpenSearch 2.11

---

.github/workflows/push.yaml
CHANGELOG.md
docker-compose.yml
serverless.example.yml

- n/a
1. update opensearch to 2.13 by default

update to opensearch 2.13 by default

---

CHANGELOG.md
README.md
package-lock.json
src/lambdas/api/openapi.yaml
src/lib/api.js
src/lib/database.js
tests/fixtures/stac/collection-with-incorrect-queryables.json
tests/system/test-api-get-aggregate.js
tests/system/test-api-get-collection-queryables.js
tests/system/test-api-get-conformance.js
tests/system/test-api-search-get.js
tests/system/test-api-search-post.js

- #72. Note that this issue calls for both Basic CQL2 and Basic Spatial Operators, but this MR only implements Basic CQL2.
Minimum implementation of the [filter extension](https://github.com/stac-api-extensions/filter).
- Basic CQL2
- CQL2 JSON (no CQL Text)
- Available to the `/search` (GET and POST), `/collections/{collectionId}/items` (GET), and `/aggregate` (GET) endpoints

Add filter extension

---

CHANGELOG.md
package-lock.json
package.json
src/lib/api.js

- #832 
1. remove stac_version and stac_extensions from itemcollection, as they are not fields for this entity

remove stac_version and stac_extensions from itemcollection

---

CHANGELOG.md
README.md
src/lib/api.js
tests/system/test-api-collection-items-get.js
tests/system/test-api-get-aggregate.js
tests/system/test-api-get-collection-aggregate.js
tests/system/test-api-get-collection-aggregations.js
tests/system/test-api-get-collection-queryables.js
tests/system/test-api-get-collection.js
tests/system/test-api-get-collections.js
tests/system/test-api-item-get.js
tests/system/test-api-search-get.js
tests/system/test-api-search-post.js

- https://github.com/stac-utils/stac-server/issues/886
1. Collections Auth features (ENABLE_COLLECTIONS_AUTHX) now fails closed
rather than open. If `_collections` is not specified or is empty, caller has no
access to collections. 
2. adds a special collection name `*` that means access
to all collections is granted.

change semantics of ENABLE_COLLECTIONS_AUTHX to fail closed and allow * for all collections
