.circleci/config.yml, Dockerfile
Updated Docker to expect Node 12 instead of Node 8.
=> [STAC-API-2] Update Node

packages/api-lib/api.yaml
Added an api.yaml file that contains the STAC core api w/ all of the extensions aside from transaction.
=> [STAC-API-6] Adding /api endpoint 

.gitignore, ops/serverless.yml, package.json, packages/api/index.js, packages/api/package.json, packages/api/webpack.config.js, packages/ingest/package.json, packages/ingest/webpack.config.js
Address Issue #1 
Adding Serverless Framework for deployment. I have added plugins for webpack in the two lambda function to create the archive that will be used to deploy to AWS. The configuration and settings for deployment will live in the `ops` folder.
=> Add serverless deployment

CHANGELOG.md
Updates the changelog with two recent features that were missed as part of those PRs
=> Changelog updates for two previous features

README.md
also fixes formatting for cloudwatch log
=> Updates readme to reflect recent change to remove develop and master, instead using main

CHANGELOG.md, libs/api.js, serverless.yml
Removed the STAC_API_VERSION key from the root catalog
=> Removed STAC_API_VERSION from root catalog

.eslintrc.json, README.md, package-lock.json, package.json, tests/unit/test-api-extractIntersects.js
**Related Issue(s):** #158 
1. upgrade to Ava 4. Required fixing 2 tests to be more specific in what they caught in a throw assertion
=> upgrade to ava 4

CHANGELOG.md, package-lock.json, package.json, src/lambdas/api/app.js, tests/system/test-api-get-root.js
=> Compress API responses

.github/workflows/push.yaml, src/lib/api.js, src/lib/esStream.js, tests/system/test-api-search-post.js
- https://github.com/stac-utils/stac-server/issues/223
1. load collections before items so index mappings are applied
=> in search post tests, load collections before items to ensure mappings are applied

README.md
- https://github.com/stac-utils/stac-server/issues/229
1. add migration advice
=> add docs for migration

CHANGELOG.md, src/lambdas/api/middleware/add-endpoint.js, tests/system/test-api-get-root.js
This should have been merged in as part of #200 , but it looks like the target branch was wrong and it never made it into the main branch.
=> Add support for `X-STAC-Endpoint` header

package-lock.json, package.json
- n/a
1. update version to 0.4.0-rc.3 in anticipation of next release
2. minor npm dep updates to lockfile
=> update version to 0.4.0-rc.3

src/lib/api.js, src/lib/es.js, tests/system/test-api-search-post.js
- #252
1. re-add page parameter
=> re-add page parameter

CHANGELOG.md, package-lock.json, package.json
- n/a
1. Update changelog and package.json for release.
=> release 0.4.0

CHANGELOG.md, src/lib/api.js
- https://github.com/stac-utils/stac-server/issues/203
1.  Used map function instead of foreach/push
=> Use map instead of foreach/push

README.md
- # https://github.com/stac-utils/stac-server/issues/237
1. Added section on locking down transaction extension endpoints and making others public
=> Added section on restricting transaction endpoints

CHANGELOG.md, src/lib/api.js
- https://github.com/stac-utils/stac-server/issues/219
1. Added proper value for sortby parameter, to work with both single and multiple sortby fields
2. Added direction for sortby field
3. Added proper value for collections parameter
=> sortby and collections parameters in next link with direction for sortby

package-lock.json
n/a
1. run `npm audit fix` to resolve a few vulnerabilites. This was blocking CI.
=> npm audit fix for a few vulnerabilities

CHANGELOG.md, README.md, src/lambdas/api/app.js, src/lib/api.js, src/lib/es.js, tests/system/test-api-get-conformance.js
- n/a
1. Add experimental support for the [Aggregation Extension](https://github.com/stac-api-extensions/aggregation)
=> Support for Aggregation Extension

README.md
- https://github.com/stac-utils/stac-server/issues/307
1. Add mention of WAF SQL injection false positive in readme.
=> add note about WAF SQL injection rule

CHANGELOG.md, README.md, fixtures/collections.js, fixtures/items.js, src/lib/esClient.js
- https://github.com/stac-utils/stac-server/issues/325
1. Add config parameters for index replicas and shards.
=> add shards and replicas configuration

src/lib/api.js
- https://github.com/stac-utils/stac-server/issues/304
1. add self and root links to /items response
=> add self and root links to /items response

CHANGELOG.md, src/lambdas/api/app.js, src/lib/api.js
- #341 
1. backport of thumbnail endpoint
=> v.0.4.2 backport: add support for thumbnail endpoint

src/lib/api.js
- n/a
1. guard for case where roles don't exist
=> add guard around item roles not existing in thumbnail check

README.md, serverless.example.yml
- n/a
1. add doc for adding thumbnail permissions
=> add config for thumbnail permissions

src/lambdas/api/app.js
- #351 
1. increase max post body size from 100kb to 1mb
=> increase max post body size

README.md
- n/a
1. few minor readme fixes
=> few minor readme fixes

src/lib/database.js
- https://github.com/stac-utils/stac-server/issues/360
1. await function that populates the unrestricted query indicies
=> fix unrestricted index population by waiting on async

tests/helpers/aws-tests.js
- n/a
1. fix regex issue in aws-tests found by CodeQL
=> fix regex in aws-tests

tests/system/test-ingest.js
- n/a
1. Fixes build failures with `The ingest lambda supports ingesting a collection sourced from S3` . Unsure why these failures started happening, but the fix was straightforward. 
=> add create bucket configuration

CHANGELOG.md, README.md, src/lambdas/api/app.js, src/lib/api.js
- n/a
1. add /aggregations and collection-level aggregate and aggregations endpoints
=> aggregations endpoint and collection-level aggregate

package.json
- n/a
1. remove audit exclude that has been resolved
=> remove exclude for audit that has been resolved, update lock

CHANGELOG.md, package-lock.json, src/lib/database.js, tests/system/test-api-search-post.js
- #457
1. add support for Query Extension neq, startsWith, endsWith, and contains
=> add support for Query Extension neq, startsWith, endsWith, and contains

CHANGELOG.md, package-lock.json, package.json
- n/a
1. Prep for 2.0.0 release
=> prep for 2.0.0 release

CHANGELOG.md, README.md, serverless.example.yml, src/lambdas/ingest/index.js, src/lib/ingest.js
- https://github.com/stac-utils/stac-server/issues/535
1. add async to publishResultsToSns and await it
2. use Promise.all and map instead of forEach (which creates the tasks but throws them away)
=> fix async sns post-ingest publishing

CHANGELOG.md, package-lock.json, package.json
- n/a
1. release prep for 2.1.0
=> release prep for 2.1.0

.github/workflows/push.yaml
=> enable ci merge group

CHANGELOG.md, src/lib/database.js
- n/a
1. Add size parameter set to 10000 for grid_code fields
=> fix issue with grid code aggregations only returning 10

CHANGELOG.md, package-lock.json, package.json
- n/a
1. release prep for 2.2.1
=> release prep 2.2.1

package.json
- n/a
1. replace non-existent "destroy" command with `remove`
=> fix sls remove command

CHANGELOG.md, package-lock.json, package.json
- n/a
1. release prep for 2.2.3
=> Pv/release prep 2.2.3

.github/workflows/push.yaml, CHANGELOG.md, package-lock.json, package.json, src/lib/databaseClient.js
- n/a
1. Re-add support for AWS connection authentication removed in https://github.com/stac-utils/stac-server/pull/511/files
2. Prep for 2.3.0 release
=> readd aws connection mode

package-lock.json
- n/a
1. fix npm audit vulnerabilitiies
=> fix audit vulnerabilities

CHANGELOG.md, src/lambdas/api/openapi.yaml, src/lib/api.js
- n/a
1. Update versions to latest for all extensions
=> update spec versions for extensions

src/lib/aws-clients.js, src/lib/databaseClient.js
- n/a
1. Change uses of localhost to 127.0.0.1, since those cause failures with node 18 -- see https://github.com/node-fetch/node-fetch/issues/1624
=> replace localhost with 127.0.0.1 to get system tests to run on Node 18 correctly

fixtures/dynamicTemplates.js
- https://github.com/stac-utils/stac-server/issues/620
1. set enabled=false on proj:geometry
=> disable indexing of proj_geometry

LICENSE, README.md
- n/a
1. Fix LICENSE file to conform to how you're supposed to modify the existing LICENSE file when forking
2. Add section in README that has the info that was previously in the license file
=> fix license file to conform to MIT rules, add License section to README

CHANGELOG.md, README.md, package-lock.json, package.json
- n/a
1. pre-release prep for 3.1.0
=> pre-release prep for 3.1.0

CHANGELOG.md, package-lock.json, package.json
- n/a
1. prep for release 3.2.0
=> release prep for 3.2.0

CHANGELOG.md, package-lock.json, package.json
- n/a
1. release prep for 3.3.0
=> release prep for 3.3.0

.vscode/launch.json, CHANGELOG.md, src/lambdas/api/app.js, src/lib/api.js, src/lib/database.js
- n/a
1. Make /collections return 500 when has not been initialized or can't connect to db
=> / and /collections returns 500 if create_indices has not been run

CHANGELOG.md, package-lock.json, package.json
- n/a
1.  release prep for 3.4.0
=> release prep for 3.4.0

README.md
- n/a
1. reorder create_indicies, so it's after FGAC setup. 
=> re-order create_indicies command, so it's after setting up auth

.husky/pre-commit, package-lock.json, package.json
- n/a
1. pre-commit was last updated 8 years ago 😢 -- husky is the modern replacement. 🐶 
=> replace pre commit with husky

src/lib/api.js, tests/system/test-api-get-conformance.js
- n/a
1. This was missing from the advertised conformance classes
=> add features-filter conformance class

CHANGELOG.md, README.md, package-lock.json, package.json
- n/a
release prep for v3.11.0
=> release prep v3.11.0

CHANGELOG.md, package-lock.json, package.json
- n/a
1. release prep for 4.3.0
=> release prep for 4.3.0
